### ISSUE TITLE
Number of frames of video 'MVI_0790_VIS_OB.avi' in 'objects_onboard.txt' does not match with that of the video clip

### ISSUE THREAD

**Issue by Qianna00** [tilemmpon/Singapore-Maritime-Dataset-Frames-Ground-Truth-Generation-and-Statistics#1]
When I capture the frames of video clip 'MVI_0790_VIS_OB.avi' using cv2, its length seems to be 600, that is 30 fps and the length is 20s.
But in 'objects_onboard_txt', it is strange that the 'image_name' of frames are listed as showed in the pictures.
Does it mean some frames are losted and the video clip has at least 894 frames in total?

![1](https://user-images.githubusercontent.com/41325698/86425875-e2ca6080-bd18-11ea-962d-42907d82b8cf.PNG)
![2](https://user-images.githubusercontent.com/41325698/86425883-e4942400-bd18-11ea-989f-d840896836f2.PNG)
![3](https://user-images.githubusercontent.com/41325698/86425889-e78f1480-bd18-11ea-8624-51b9500bd2f5.PNG)

**Comment by tilemmpon** [comment]
Hi @Qianna00, thank you for your interest. There is no "lost frames". The gaps in the frames mean that the video has not object annotations for the skipped frames. 'objects_onboard.txt' file contains only the object annotation so it makes sense to have no annotations for frames of the video without any object. Check the video 'MVI_0790_VIS_OB.avi' you mentioned and you will notice as well that some parts of it have no vessels visible.

Concerning the extra frames in the 'objects_onboard.txt' file, I am not sure why it is this way. My scripts generates the objects according to the ground truth .mat files provided by the creators of this dataset. The only explanation I can think of is that the original video was longer in duration and they annotated it fully. Then for some reason they released a "cropped" version of the video, thus the extra frames (up to 894) you see and do not correspond to the frames you correctly generate (600). Finally, I must mention that this will not make any difference in the ML training infrastructure I created. The code matches the generated frames to the object annotations. If a frame has no object or if the frame is missing but has objects annotated, it will be skipped in the training and will not be taken into consideration.

Once more thank you for your interest. I am always available if you have further question. Feel free to close the issue if you have no further inquires.

**Comment by Qianna00** [comment]
@tilemmpon Glad to get your prompt reply! There is no other problem at present and I will close the issue, thank you very much!
