### ISSUE TITLE
KeyError: 'structXML'

### ISSUE THREAD

**Issue by shkk941111** [tilemmpon/Singapore-Maritime-Dataset-Frames-Ground-Truth-Generation-and-Statistics#10]
File "d:/Singapore-Maritime-Dataset-Frames-Ground-Truth-Generation-and-Statistics-master/load_mat_into_csv_xml.py", line 601, in <module>
    _, object_list_train_temp, object_list_test_temp = generate_split_dataset_csv_xml(os.path.join(args.inputDir, mat_file), frames_tuple, paths_list, integer_bb=False)
  File "d:/Singapore-Maritime-Dataset-Frames-Ground-Truth-Generation-and-Statistics-master/load_mat_into_csv_xml.py", line 519, in generate_split_dataset_csv_xml
    frames_number = len(gt['structXML'][0])
KeyError: 'structXML'

What is the cause of this problem? How do I fix it?

**Comment by tilemmpon** [comment]
Hi,

Could you please post the ground truth file you are using? I generally used the file as shown [here](https://drive.google.com/file/d/0B10RxHxW3I92NjRjZnN1bjVjelk/view?resourcekey=0-ily_5TgkNa6Ai3kHfAMk8w) where they have a "structXML" entry but the code cannot find this structure which means that (1) either you use a wrong file or (2) they have updated the ground truth file without using this structure.

Best regards,
tilemmpon

**Comment by tilemmpon** [comment]
Closed as incomplete since no further feedback has been received.
