### ISSUE TITLE
Why total object is 0? 

### ISSUE THREAD

**Issue by shkk941111** [tilemmpon/Singapore-Maritime-Dataset-Frames-Ground-Truth-Generation-and-Statistics#11]
PS D:\Singapore-Maritime-Dataset-Frames-Ground-Truth-Generation-and-Statistics-> & C:/Users/cy/AppData/Local/Programs/Python/Python38/python.exe d:/Singapore-Maritime-Dataset-Frames-Ground-Truth-Generation-and-Statistics-/load_mat_into_csv_xml.py
Total objects in train dataset:  0
Total objects in test dataset:  0 
Successfully converted mat to csv.

**Comment by tilemmpon** [comment]
Probably the files provided are empty or could not be read. Could you please double-check the input path you provide and if the structure complies to the one the script expects? Moreover have you generated the frames successfully? The code convert the .mat files to .csv format only for the frame it detects in the frames folder (parameter -f).

Best regards,
tilemmpon

**Comment by Leo-Chao** [comment]
How to generated the frames?

**Comment by tilemmpon** [comment]
Closed as incomplete since no further feedback has been received.
