### ISSUE TITLE
 objects_onshore.txt

### ISSUE THREAD

**Issue by hesamira** [tilemmpon/Singapore-Maritime-Dataset-Frames-Ground-Truth-Generation-and-Statistics#13]
Hi,
Thanks for you code.
When I ran this part of your code, I faced this error. How can find objects_onshore.txt file?
Please, help me. Thanks.

# try to draw image with bounding boxes
# load the object ground truth files first
video_name = 'MVI_1613_VIS'
objects_onshore = []
with open("objects_onshore.txt") as f:
    for line in f: 
        line = line.strip()
        objects_onshore.append(line)
        
objects_onboard = []
with open("objects_onboard.txt") as f:
    for line in f: 
        line = line.strip()
        objects_onboard.append(line)
        
objects_nir = []
with open("objects_nir.txt") as f:
    for line in f: 
        line = line.strip()
        objects_nir.append(line)

FileNotFoundError                         Traceback (most recent call last)

<ipython-input-26-f1eff3dfb0ac> in <cell line: 6>()
      4 video_name = 'MVI_1613_VIS'
      5 objects_onshore = []
----> 6 with open("objects_onshore.txt") as f:
      7     for line in f:
      8         line = line.strip()

FileNotFoundError: [Errno 2] No such file or directory: 'objects_onshore.txt'

**Comment by tilemmpon** [comment]
I apologize for the late reply. This file exists in the repo (https://github.com/tilemmpon/Singapore-Maritime-Dataset-Frames-Ground-Truth-Generation-and-Statistics/blob/master/objects_onshore.txt) so either copy it to the location you run it from or make sure the running location in Python is inside the repository folder.

**Comment by tilemmpon** [comment]
Closed as completed since no further feedback has been received.
