### ISSUE TITLE
Labeled dataset

### ISSUE THREAD

**Issue by yaoshanliang** [tilemmpon/Singapore-Maritime-Dataset-Frames-Ground-Truth-Generation-and-Statistics#2]
Hi，
Did you provide the labeled dataset after processing?

**Comment by tilemmpon** [comment]
Hello,

I have not provided the labeled dataset, however all the code required to generate it is given in this repository. You need the original dataset of SMD and then you can use:
- https://github.com/tilemmpon/Singapore-Maritime-Dataset-Frames-Ground-Truth-Generation-and-Statistics/blob/master/load_mat_into_csv_xml.py to generate the labels for each frame in both CSV and xml/VOC format.
- https://github.com/tilemmpon/Singapore-Maritime-Dataset-Frames-Ground-Truth-Generation-and-Statistics/blob/master/generate_tfrecord.py to convert the CSV file into the tfrecord for tensorflow.

There are also Jupyter Notebooks to convert the videos into frames.

**Comment by yaoshanliang** [comment]
Thank you very much.
