### ISSUE TITLE
Does it contains the instance segmentation?

### ISSUE THREAD

**Issue by yaoshanliang** [tilemmpon/Singapore-Maritime-Dataset-Frames-Ground-Truth-Generation-and-Statistics#5]

**Comment by tilemmpon** [comment]
Hello,
No this dataset does not contain the instance segmentation. It only has the bounding boxes ground truth for object detection. I only used it for object detection and not instance segmentation.

**Comment by yaoshanliang** [comment]
I know. Thank you.

Does the author of SMD provide instance segmentation label?

**Comment by tilemmpon** [comment]
Unfortunately they did not. I checked again (https://sites.google.com/site/dilipprasad/home/singapore-maritime-dataset) and it seems that there was no update on the dataset. You can try to contact them directly if they plan to release instance segmentation labels.

**Comment by yaoshanliang** [comment]
Thank you so much.

I see that it contains track and horizon labels. Do they need to be processed in the way as you did in object detection?

**Comment by tilemmpon** [comment]
Track and horizon labels were not used by my code. The ground truth generation is in this file:

https://github.com/tilemmpon/Singapore-Maritime-Dataset-Frames-Ground-Truth-Generation-and-Statistics/blob/master/load_mat_into_csv_xml.py

You will need to adapt it to also export the Track and Horizon Ground Truth if you need them. Adjustments will be needed here for the CSV file for tensorflow:

https://github.com/tilemmpon/Singapore-Maritime-Dataset-Frames-Ground-Truth-Generation-and-Statistics/blob/master/load_mat_into_csv_xml.py#L117

(Please see implementation of this here: https://github.com/tilemmpon/Singapore-Maritime-Dataset-Frames-Ground-Truth-Generation-and-Statistics/blob/master/convert_mat_to_csv_LEGACY.py#L96 . You can copy it to the file above.)

 and here for the VOC xml file:

https://github.com/tilemmpon/Singapore-Maritime-Dataset-Frames-Ground-Truth-Generation-and-Statistics/blob/ca35c4f4d16cf8f1cebbf1a0e7530792ab6f826f/load_mat_into_csv_xml.py#L161

**Comment by yaoshanliang** [comment]
You are so kind. Thank you.

**Comment by tilemmpon** [comment]
You're welcome. Let me know if you have other questions regarding this or open a new issue. Feel free to close this issue.
