### ISSUE TITLE
.txt file for labelling

### ISSUE THREAD

**Issue by Yousef-Alhattab** [tilemmpon/Singapore-Maritime-Dataset-Frames-Ground-Truth-Generation-and-Statistics#6]
hey there,

how can I get a .txt file of a yolo format ( x y w h) to use this dataset?

I could not find that out as far as I got from your repository!

would you guide me please?

**Comment by tilemmpon** [comment]
Hello,

The code outputs in CSV format which can be renamed to .txt. The control of the CSV entries is in the function (https://github.com/tilemmpon/Singapore-Maritime-Dataset-Frames-Ground-Truth-Generation-and-Statistics/blob/master/load_mat_into_csv_xml.py#L92). From what I can see here (https://github.com/tilemmpon/Singapore-Maritime-Dataset-Frames-Ground-Truth-Generation-and-Statistics/blob/master/load_mat_into_csv_xml.py#L116) there is output of everything, xmin, xmax, ymin, ymax, height and width. You can try and modify it there if you want a custom formatting.

**Comment by Yousef-Alhattab** [comment]
Hi!

when I extracted the frames using this:

https://github.com/tilemmpon/Singapore-Maritime-Dataset-Frames-Ground-Truth-Generation-and-Statistics/blob/master/Singapore_dataset_frames_generation_and_histograms.ipynb

everything was fine. But when I convert the Dataset (SMD) .mat object ground truth files into a CSV I got this message

Total objects in train dataset:  0
Total objects in test dataset:  0
Successfully converted mat to csv.

I am sure the USAGE of the load_mat_into_csv_xml.py was fine but I dont know why I got this error!

any help, please

**Comment by Yousef-Alhattab** [comment]
I got it
I am on windows 

thanks  a lot


I have another question, please 

when I convert ALL on board videos into images with 1 image per frame

it converted the videos with OBJECT_ANNOTATIONS only which are four?

why would you convert all the videos??

**Comment by tilemmpon** [comment]
I guess the question is how to convert all videos into frames, not only the ones with a ground truth. This is quite easy: In the referenced notebook check the cell/output 7 (In [7]). This is where I am filtering out all the videos without a ground truth. If you skip this cell when running then the code will generate the frames for all the videos.

**Comment by Ganaken** [comment]
> I got it I am on windows
> 
> thanks a lot
> 
> I have another question, please
> 
> when I convert ALL on board videos into images with 1 image per frame
> 
> it converted the videos with OBJECT_ANNOTATIONS only which are four?
> 
> why would you convert all the videos??

how did you fix having 0 objects in training and testing? Is it a windows issue?

**Comment by tilemmpon** [comment]
Closed as completed since no further feedback has been received.
