### ISSUE TITLE
How can I get a MOT .txt dataset from your data?

### ISSUE THREAD

**Issue by Mulbetty** [tilemmpon/Singapore-Maritime-Dataset-Frames-Ground-Truth-Generation-and-Statistics#7]
Thanks for your data!

**Comment by tilemmpon** [comment]
Are you referring to this challenge: https://motchallenge.net/instructions/ ?

You can modify the format of the output to any format you want. See the instructions I already replied here: https://github.com/tilemmpon/Singapore-Maritime-Dataset-Frames-Ground-Truth-Generation-and-Statistics/issues/6#issuecomment-762077642

**Comment by Mulbetty** [comment]
> the

You mean that I can get what I want from the .csv objects?
Thank you . I will have a try!

**Comment by tilemmpon** [comment]
Closed as completed since no further feedback has been received.
